// SPDX-License-Identifier: BSD-3-Clause
/*
 * Copyright 2020-2021, 2023-2024 NXP
 */
#ifndef S32CC_CLK_REGS_H
#define S32CC_CLK_REGS_H

#include <lib/utils_def.h>

#define FXOSC_BASE_ADDR			(0x40050000UL)
#define ARMPLL_BASE_ADDR		(0x40038000UL)
#define CGM1_BASE_ADDR			(0x40034000UL)

/* FXOSC */
#define FXOSC_CTRL(FXOSC)		((FXOSC) + 0x0UL)
#define FXOSC_CTRL_OSC_BYP		BIT_32(31U)
#define FXOSC_CTRL_COMP_EN		BIT_32(24U)
#define FXOSC_CTRL_EOCV_OFFSET		16U
#define FXOSC_CTRL_EOCV_MASK		GENMASK_32(23U, FXOSC_CTRL_EOCV_OFFSET)
#define FXOSC_CTRL_EOCV(VAL)		(FXOSC_CTRL_EOCV_MASK & \
					 ((uint32_t)(VAL) << FXOSC_CTRL_EOCV_OFFSET))
#define FXOSC_CTRL_GM_SEL_OFFSET	4U
#define FXOSC_CTRL_GM_SEL_MASK		GENMASK_32(7U, FXOSC_CTRL_GM_SEL_OFFSET)
#define FXOSC_CTRL_GM_SEL(VAL)		(FXOSC_CTRL_GM_SEL_MASK & \
					 ((uint32_t)(VAL) << FXOSC_CTRL_GM_SEL_OFFSET))
#define FXOSC_CTRL_OSCON		BIT_32(0U)

#define FXOSC_STAT(FXOSC)		((FXOSC) + 0x4UL)
#define FXOSC_STAT_OSC_STAT		BIT_32(31U)

/* PLL */
#define PLLDIG_PLLCR(PLL)		((PLL) + UL(0x0))
#define PLLDIG_PLLCR_PLLPD		BIT_32(U(31))

#define PLLDIG_PLLSR(PLL)		((PLL) + UL(0x4))
#define PLLDIG_PLLSR_LOCK		BIT_32(U(2))

#define PLLDIG_PLLDV(PLL)		((PLL) + UL(0x8))
#define PLLDIG_PLLDV_RDIV_OFFSET	U(12)
#define PLLDIG_PLLDV_RDIV_MASK		GENMASK_32(U(14), PLLDIG_PLLDV_RDIV_OFFSET)
#define PLLDIG_PLLDV_RDIV_SET(VAL)	(PLLDIG_PLLDV_RDIV_MASK & \
					((VAL) << PLLDIG_PLLDV_RDIV_OFFSET))
#define PLLDIG_PLLDV_MFI_MASK		GENMASK_32(U(7), U(0))
#define PLLDIG_PLLDV_MFI(DIV)		(PLLDIG_PLLDV_MFI_MASK & (DIV))

#define PLLDIG_PLLFD(PLL)		((PLL) + UL(0x10))
#define PLLDIG_PLLFD_SMDEN		BIT_32(U(30))
#define PLLDIG_PLLFD_MFN_MASK		GENMASK_32(U(14), U(0))
#define PLLDIG_PLLFD_MFN_SET(VAL)	(PLLDIG_PLLFD_MFN_MASK & (VAL))

#define PLLDIG_PLLCLKMUX(PLL)		((PLL) + UL(0x20))

#define PLLDIG_PLLODIV(PLL, N)		((PLL) + UL(0x80) + ((N) * UL(0x4)))
#define PLLDIG_PLLODIV_DE		BIT_32(U(31))
#define PLLDIG_PLLODIV_DIV_OFFSET	U(16)
#define PLLDIG_PLLODIV_DIV_MASK		GENMASK_32(U(23), PLLDIG_PLLODIV_DIV_OFFSET)
#define PLLDIG_PLLODIV_DIV(VAL)		(((VAL) & PLLDIG_PLLODIV_DIV_MASK) >> \
					 PLLDIG_PLLODIV_DIV_OFFSET)
#define PLLDIG_PLLODIV_DIV_SET(VAL)	(PLLDIG_PLLODIV_DIV_MASK & ((VAL) << \
					 PLLDIG_PLLODIV_DIV_OFFSET))

/* MMC_CGM */
#define CGM_MUXn_CSC(CGM_ADDR, MUX)	((CGM_ADDR) + UL(0x300) + ((MUX) * UL(0x40)))
#define MC_CGM_MUXn_CSC_SELCTL_OFFSET	U(24)
#define MC_CGM_MUXn_CSC_SELCTL_MASK	GENMASK_32(U(29), MC_CGM_MUXn_CSC_SELCTL_OFFSET)
#define MC_CGM_MUXn_CSC_SELCTL(val)	(MC_CGM_MUXn_CSC_SELCTL_MASK & ((val) \
					 << MC_CGM_MUXn_CSC_SELCTL_OFFSET))
#define MC_CGM_MUXn_CSC_CLK_SW		BIT_32(U(2))
#define MC_CGM_MUXn_CSC_SAFE_SW		BIT_32(U(3))

#define CGM_MUXn_CSS(CGM_ADDR, MUX)	((CGM_ADDR) + UL(0x304) + ((MUX) * UL(0x40)))
#define MC_CGM_MUXn_CSS_SELSTAT_OFFSET	U(24)
#define MC_CGM_MUXn_CSS_SELSTAT_MASK	GENMASK_32(U(29), MC_CGM_MUXn_CSS_SELSTAT_OFFSET)
#define MC_CGM_MUXn_CSS_SELSTAT(css)	((MC_CGM_MUXn_CSS_SELSTAT_MASK & (css))\
					 >> MC_CGM_MUXn_CSS_SELSTAT_OFFSET)
#define MC_CGM_MUXn_CSS_SWTRG(css)	((MC_CGM_MUXn_CSS_SWTRG_MASK & (css)) \
					 >> MC_CGM_MUXn_CSS_SWTRG_OFFSET)
#define MC_CGM_MUXn_CSS_SWTRG_OFFSET	U(17)
#define MC_CGM_MUXn_CSS_SWTRG_MASK	GENMASK_32(U(19), MC_CGM_MUXn_CSS_SWTRG_OFFSET)
#define MC_CGM_MUXn_CSS_SWTRG_SUCCESS	U(0x1)
#define MC_CGM_MUXn_CSS_SWTRG_SAFE_CLK	U(0x4)
#define MC_CGM_MUXn_CSS_SWTRG_SAFE_CLK_INACTIVE	U(0x5)
#define MC_CGM_MUXn_CSS_SWIP		BIT_32(U(16))
#define MC_CGM_MUXn_CSS_SAFE_SW		BIT_32(U(3))

#endif /* S32CC_CLK_REGS_H */
