#ifndef __MT_SPM_DOE_RESOURCE_CTRL_H__
#define __MT_SPM_DOE_RESOURCE_CTRL_H__

#include <mt_spm_internal.h>

enum resource_ctrl_enum {
	MT_SPM_RESOURCE_CTRL_BUS26M,
	MT_SPM_RESOURCE_CTRL_INFRA,
	MT_SPM_RESOURCE_CTRL_SYSPLL,
	MT_SPM_RESOURCE_CTRL_DRAM_S0,
	MT_SPM_RESOURCE_CTRL_DRAM_S1,
	MT_SPM_RESOURCE_CTRL_MAX_NUM,
};

static int mt8192_resource_ctrl[MT_SPM_RESOURCE_CTRL_MAX_NUM] = {
	[MT_SPM_RESOURCE_CTRL_BUS26M] = PW_REG_SPM_F26M_REQ,
	[MT_SPM_RESOURCE_CTRL_INFRA] = PW_REG_SPM_INFRA_REQ,
	[MT_SPM_RESOURCE_CTRL_SYSPLL] = PW_REG_SPM_VRF18_REQ,
	[MT_SPM_RESOURCE_CTRL_DRAM_S0] = PW_REG_SPM_APSRC_REQ,
	[MT_SPM_RESOURCE_CTRL_DRAM_S1] = PW_REG_SPM_DDR_EN_REQ,
};

#endif
