/*
 * Copyright (c) 2022, MediaTek Inc. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef PLAT_HYP_SECIO_H
#define PLAT_HYP_SECIO_H

#include <platform_def.h>
#include "../../mtk_hyp_secio.h"

/*******************************************************************************
 * SECURE CAMERA
 ******************************************************************************/

/* GCE was mapped by cmdq */
#define GCE_BASE_ADDR               (IO_PHYS + 0x0E980000)
#define GCE_BASE_SIZE               (0x1000)
#define GCE_ALREADY_MAPPED          1
#define ISP_CAM_A_BASE_ADDR         (IO_PHYS + 0x0A030000)
#define ISP_CAM_A_BASE_SIZE         (0x1F000)
#define ISP_CAM_B_BASE_ADDR         (IO_PHYS + 0x0A070000)
#define ISP_CAM_B_BASE_SIZE         (0x1F000)
/*
 * #define DIP_TOP_BASE_ADDR           SECIO_INVALID
 * #define DIP_TOP_BASE_SIZE           SECIO_INVALID
 */
#define DAPC_AO_MM0_BASE_ADDR       (IO_PHYS + 0x0E820000)
#define DAPC_AO_MM0_BASE_SIZE       (0x1000)
#define DAPC_AO_MM1_BASE_ADDR       (IO_PHYS + 0x0E821000)
#define DAPC_AO_MM1_BASE_SIZE       (0x1000)
/*
 * #define DIP_DMA_BASE_ADDR           SECIO_INVALID
 * #define DIP_DMA_BASE_SIZE           SECIO_INVALID
 */
#define SENINF_MUX1_BASE_ADDR       (IO_PHYS + 0x0A010000)
#define SENINF_MUX1_BASE_SIZE       (0x1000)
#define SENINF_MUX2_BASE_ADDR       (IO_PHYS + 0x0A011000)
#define SENINF_MUX2_BASE_SIZE       (0x1000)
#define SENINF_MUX3_BASE_ADDR       (IO_PHYS + 0x0A012000)
#define SENINF_MUX3_BASE_SIZE       (0x1000)
#define SENINF_MUX4_BASE_ADDR       (IO_PHYS + 0x0A013000)
#define SENINF_MUX4_BASE_SIZE       (0x1000)
#define SENINF_MUX5_BASE_ADDR       (IO_PHYS + 0x0A014000)
#define SENINF_MUX5_BASE_SIZE       (0x1000)
#define SENINF_MUX6_BASE_ADDR       (IO_PHYS + 0x0A015000)
#define SENINF_MUX6_BASE_SIZE       (0x1000)
#define SENINF_MUX7_BASE_ADDR       (IO_PHYS + 0x0A016000)
#define SENINF_MUX7_BASE_SIZE       (0x1000)
#define SENINF_MUX8_BASE_ADDR       (IO_PHYS + 0x0A017000)
#define SENINF_MUX8_BASE_SIZE       (0x1000)
#define ISP_CAM_C_BASE_ADDR         (IO_PHYS + 0x0A0B0000)
#define ISP_CAM_C_BASE_SIZE         (0x1F000)
/*
 * #define FD_TOP_BASE_ADDR            SECIO_INVALID
 * #define FD_TOP_BASE_SIZE            SECIO_INVALID
 */
/* GCE_M was mapped by cmdq */
#define GCE_M_BASE_ADDR             (IO_PHYS + 0x0E990000)
#define GCE_M_BASE_SIZE             (0x1000)
#define GCE_M_ALREADY_MAPPED        1
/*
 * #define ISP_CAM_A2_BASE_ADDR        SECIO_INVALID
 * #define ISP_CAM_A2_BASE_SIZE        SECIO_INVALID
 * #define ISP_CAM_B2_BASE_ADDR        SECIO_INVALID
 * #define ISP_CAM_B2_BASE_SIZE        SECIO_INVALID
 * #define ISP_CAM_C2_BASE_ADDR        SECIO_INVALID
 * #define ISP_CAM_C2_BASE_SIZE        SECIO_INVALID
 * #define ISP_CAM_SYS_BASE_ADDR       SECIO_INVALID
 * #define ISP_CAM_SYS_BASE_SIZE       SECIO_INVALID
 * #define SMI_LARB0_BASE_ADDR         SECIO_INVALID
 * #define SMI_LARB0_BASE_SIZE         SECIO_INVALID
 * #define SMI_LARB1_BASE_ADDR         SECIO_INVALID
 * #define SMI_LARB1_BASE_SIZE         SECIO_INVALID
 * #define SMI_LARB2_BASE_ADDR         SECIO_INVALID
 * #define SMI_LARB2_BASE_SIZE         SECIO_INVALID
 * #define SMI_LARB3_BASE_ADDR         SECIO_INVALID
 * #define SMI_LARB3_BASE_SIZE         SECIO_INVALID
 * #define SMI_LARB4_BASE_ADDR         SECIO_INVALID
 * #define SMI_LARB4_BASE_SIZE         SECIO_INVALID
 * #define SMI_LARB5_BASE_ADDR         SECIO_INVALID
 * #define SMI_LARB5_BASE_SIZE         SECIO_INVALID
 * #define SMI_LARB6_BASE_ADDR         SECIO_INVALID
 * #define SMI_LARB6_BASE_SIZE         SECIO_INVALID
 */
#define ISP_YUV_CAM_A_BASE_ADDR     (IO_PHYS + 0x0A050000)
#define ISP_YUV_CAM_A_BASE_SIZE     (0x1F000)
#define ISP_YUV_CAM_B_BASE_ADDR     (IO_PHYS + 0x0A090000)
#define ISP_YUV_CAM_B_BASE_SIZE     (0x1F000)
#define ISP_YUV_CAM_C_BASE_ADDR     (IO_PHYS + 0x0A0D0000)
#define ISP_YUV_CAM_C_BASE_SIZE     (0x1F000)
#define SENINF_MUX9_BASE_ADDR       (IO_PHYS + 0x0A018000)
#define SENINF_MUX9_BASE_SIZE       (0x1000)
#define SENINF_MUX10_BASE_ADDR      (IO_PHYS + 0x0A019000)
#define SENINF_MUX10_BASE_SIZE      (0x1000)
#define SENINF_MUX11_BASE_ADDR      (IO_PHYS + 0x0A01A000)
#define SENINF_MUX11_BASE_SIZE      (0x1000)
#define SENINF_MUX12_BASE_ADDR      (IO_PHYS + 0x0A01B000)
#define SENINF_MUX12_BASE_SIZE      (0x1000)
#define SENINF_MUX13_BASE_ADDR      (IO_PHYS + 0x0A01C000)
#define SENINF_MUX13_BASE_SIZE      (0x1000)
#define SENINF_MUX14_BASE_ADDR      (IO_PHYS + 0x0A01D000)
#define SENINF_MUX14_BASE_SIZE      (0x1000)
#define SENINF_MUX15_BASE_ADDR      (IO_PHYS + 0x0A01E000)
#define SENINF_MUX15_BASE_SIZE      (0x1000)
#define SENINF_MUX16_BASE_ADDR      (IO_PHYS + 0x0A01F000)
#define SENINF_MUX16_BASE_SIZE      (0x1000)
#define SENINF_MUX17_BASE_ADDR      (IO_PHYS + 0x0A020000)
#define SENINF_MUX17_BASE_SIZE      (0x1000)
#define SENINF_MUX18_BASE_ADDR      (IO_PHYS + 0x0A021000)
#define SENINF_MUX18_BASE_SIZE      (0x1000)
#define SENINF_MUX19_BASE_ADDR      (IO_PHYS + 0x0A022000)
#define SENINF_MUX19_BASE_SIZE      (0x1000)
#define SENINF_MUX20_BASE_ADDR      (IO_PHYS + 0x0A023000)
#define SENINF_MUX20_BASE_SIZE      (0x1000)
#define SENINF_MUX21_BASE_ADDR      (IO_PHYS + 0x0A024000)
#define SENINF_MUX21_BASE_SIZE      (0x1000)
#define SENINF_MUX22_BASE_ADDR      (IO_PHYS + 0x0A025000)
#define SENINF_MUX22_BASE_SIZE      (0x1000)
#define ISP_INFRA_S_BASE_ADDR       (IO_PHYS + 0x0E800000)
#define ISP_INFRA_S_BASE_SIZE       (0x1000)

static const struct secio_register plat_secio_regs[SECIO_MAX] = {
	/* 0*/ SECIO_REG(SECIO_INVALID,           SECIO_INVALID,           SECIO_INVALID),
	/* 1*/ SECIO_REG(SECIO_GCE,               GCE_BASE_ADDR,           GCE_BASE_SIZE),
	/* 2*/ SECIO_REG(SECIO_ISP_CAM_A,         ISP_CAM_A_BASE_ADDR,     ISP_CAM_A_BASE_SIZE),
	/* 3*/ SECIO_REG(SECIO_ISP_CAM_B,         ISP_CAM_B_BASE_ADDR,     ISP_CAM_B_BASE_SIZE),
	/* 4*/ SECIO_REG(SECIO_DIP_TOP,           SECIO_INVALID,           SECIO_INVALID),
	/* 5*/ SECIO_REG(SECIO_DAPC_AO_MM0,       DAPC_AO_MM0_BASE_ADDR,   DAPC_AO_MM0_BASE_SIZE),
	/* 6*/ SECIO_REG(SECIO_DAPC_AO_MM1,       DAPC_AO_MM1_BASE_ADDR,   DAPC_AO_MM1_BASE_SIZE),
	/* 7*/ SECIO_REG(SECIO_DIP_DMA,           SECIO_INVALID,           SECIO_INVALID),
	/* 8*/ SECIO_REG(SECIO_SENINF_MUX1,       SENINF_MUX1_BASE_ADDR,   SENINF_MUX1_BASE_SIZE),
	/* 9*/ SECIO_REG(SECIO_SENINF_MUX2,       SENINF_MUX2_BASE_ADDR,   SENINF_MUX2_BASE_SIZE),
	/*10*/ SECIO_REG(SECIO_SENINF_MUX3,       SENINF_MUX3_BASE_ADDR,   SENINF_MUX3_BASE_SIZE),
	/*11*/ SECIO_REG(SECIO_SENINF_MUX4,       SENINF_MUX4_BASE_ADDR,   SENINF_MUX4_BASE_SIZE),
	/*12*/ SECIO_REG(SECIO_SENINF_MUX5,       SENINF_MUX5_BASE_ADDR,   SENINF_MUX5_BASE_SIZE),
	/*13*/ SECIO_REG(SECIO_SENINF_MUX6,       SENINF_MUX6_BASE_ADDR,   SENINF_MUX6_BASE_SIZE),
	/*14*/ SECIO_REG(SECIO_SENINF_MUX7,       SENINF_MUX7_BASE_ADDR,   SENINF_MUX7_BASE_SIZE),
	/*15*/ SECIO_REG(SECIO_SENINF_MUX8,       SENINF_MUX8_BASE_ADDR,   SENINF_MUX8_BASE_SIZE),
	/*16*/ SECIO_REG(SECIO_ISP_CAM_C,         ISP_CAM_C_BASE_ADDR,     ISP_CAM_C_BASE_SIZE),
	/*17*/ SECIO_REG(SECIO_FD_TOP,            SECIO_INVALID,           SECIO_INVALID),
	/*18*/ SECIO_REG(SECIO_GCE_M,             GCE_M_BASE_ADDR,         GCE_M_BASE_SIZE),
	/*19*/ SECIO_REG(SECIO_ISP_CAM_A2,        SECIO_INVALID,           SECIO_INVALID),
	/*20*/ SECIO_REG(SECIO_ISP_CAM_B2,        SECIO_INVALID,           SECIO_INVALID),
	/*21*/ SECIO_REG(SECIO_ISP_CAM_C2,        SECIO_INVALID,           SECIO_INVALID),
	/*22*/ SECIO_REG(SECIO_ISP_CAM_SYS,       SECIO_INVALID,           SECIO_INVALID),
	/*23*/ SECIO_REG(SECIO_M4U_CAM_SMI_LARB0, SECIO_INVALID,           SECIO_INVALID),
	/*24*/ SECIO_REG(SECIO_M4U_CAM_SMI_LARB1, SECIO_INVALID,           SECIO_INVALID),
	/*25*/ SECIO_REG(SECIO_M4U_CAM_SMI_LARB2, SECIO_INVALID,           SECIO_INVALID),
	/*26*/ SECIO_REG(SECIO_M4U_CAM_SMI_LARB3, SECIO_INVALID,           SECIO_INVALID),
	/*27*/ SECIO_REG(SECIO_M4U_CAM_SMI_LARB4, SECIO_INVALID,           SECIO_INVALID),
	/*28*/ SECIO_REG(SECIO_M4U_CAM_SMI_LARB5, SECIO_INVALID,           SECIO_INVALID),
	/*29*/ SECIO_REG(SECIO_M4U_CAM_SMI_LARB6, SECIO_INVALID,           SECIO_INVALID),
	/*30*/ SECIO_REG(SECIO_ISP_YUV_CAM_A,     ISP_YUV_CAM_A_BASE_ADDR, ISP_YUV_CAM_A_BASE_SIZE),
	/*31*/ SECIO_REG(SECIO_ISP_YUV_CAM_B,     ISP_YUV_CAM_B_BASE_ADDR, ISP_YUV_CAM_B_BASE_SIZE),
	/*32*/ SECIO_REG(SECIO_ISP_YUV_CAM_C,     ISP_YUV_CAM_C_BASE_ADDR, ISP_YUV_CAM_C_BASE_SIZE),
	/*33*/ SECIO_REG(SECIO_SENINF_MUX9,       SENINF_MUX9_BASE_ADDR,   SENINF_MUX9_BASE_SIZE),
	/*34*/ SECIO_REG(SECIO_SENINF_MUX10,      SENINF_MUX10_BASE_ADDR,  SENINF_MUX10_BASE_SIZE),
	/*35*/ SECIO_REG(SECIO_SENINF_MUX11,      SENINF_MUX11_BASE_ADDR,  SENINF_MUX11_BASE_SIZE),
	/*36*/ SECIO_REG(SECIO_SENINF_MUX12,      SENINF_MUX12_BASE_ADDR,  SENINF_MUX12_BASE_SIZE),
	/*37*/ SECIO_REG(SECIO_SENINF_MUX13,      SENINF_MUX13_BASE_ADDR,  SENINF_MUX13_BASE_SIZE),
	/*38*/ SECIO_REG(SECIO_SENINF_MUX14,      SENINF_MUX14_BASE_ADDR,  SENINF_MUX14_BASE_SIZE),
	/*39*/ SECIO_REG(SECIO_SENINF_MUX15,      SENINF_MUX15_BASE_ADDR,  SENINF_MUX15_BASE_SIZE),
	/*40*/ SECIO_REG(SECIO_SENINF_MUX16,      SENINF_MUX16_BASE_ADDR,  SENINF_MUX16_BASE_SIZE),
	/*41*/ SECIO_REG(SECIO_SENINF_MUX17,      SENINF_MUX17_BASE_ADDR,  SENINF_MUX17_BASE_SIZE),
	/*42*/ SECIO_REG(SECIO_SENINF_MUX18,      SENINF_MUX18_BASE_ADDR,  SENINF_MUX18_BASE_SIZE),
	/*43*/ SECIO_REG(SECIO_SENINF_MUX19,      SENINF_MUX19_BASE_ADDR,  SENINF_MUX19_BASE_SIZE),
	/*44*/ SECIO_REG(SECIO_SENINF_MUX20,      SENINF_MUX20_BASE_ADDR,  SENINF_MUX10_BASE_SIZE),
	/*45*/ SECIO_REG(SECIO_SENINF_MUX21,      SENINF_MUX21_BASE_ADDR,  SENINF_MUX11_BASE_SIZE),
	/*46*/ SECIO_REG(SECIO_SENINF_MUX22,      SENINF_MUX22_BASE_ADDR,  SENINF_MUX12_BASE_SIZE),
	/*47*/ SECIO_REG(SECIO_ISP_INFRA_S,       ISP_INFRA_S_BASE_ADDR,   ISP_INFRA_S_BASE_SIZE),
};

#endif /* PLAT_HYP_SECIO_H */
