/*
 * Copyright (c) 2021, MediaTek Inc. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <common/debug.h>
#include <mtk_mmap_pool.h>

#include "plat_hyp_secio.h"

#define SECIO_ATTR (MT_DEVICE | MT_RW | MT_SECURE)
static const mmap_region_t gz_secio_plat_mmap[] MTK_MMAP_SECTION = {
#if defined(GCE_BASE_ADDR) && !defined(GCE_ALREADY_MAPPED)
	MAP_REGION_FLAT(GCE_BASE_ADDR,           GCE_BASE_SIZE,           SECIO_ATTR),
#endif
#if defined(ISP_CAM_A_BASE_ADDR)
	MAP_REGION_FLAT(ISP_CAM_A_BASE_ADDR,     ISP_CAM_A_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(ISP_CAM_B_BASE_ADDR)
	MAP_REGION_FLAT(ISP_CAM_B_BASE_ADDR,     ISP_CAM_B_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(DIP_TOP_BASE_ADDR)
	MAP_REGION_FLAT(DIP_TOP_BASE_ADDR,       DIP_TOP_BASE_SIZE,       SECIO_ATTR),
#endif
#if defined(DAPC_AO_MM0_BASE_ADDR)
	MAP_REGION_FLAT(DAPC_AO_MM0_BASE_ADDR,   DAPC_AO_MM0_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(DAPC_AO_MM1_BASE_ADDR)
	MAP_REGION_FLAT(DAPC_AO_MM1_BASE_ADDR,   DAPC_AO_MM1_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(DIP_DMA_BASE_ADDR)
	MAP_REGION_FLAT(DIP_DMA_BASE_ADDR,       DIP_DMA_BASE_SIZE,       SECIO_ATTR),
#endif
#if defined(SENINF_MUX1_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX1_BASE_ADDR,   SENINF_MUX1_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX2_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX2_BASE_ADDR,   SENINF_MUX2_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX3_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX3_BASE_ADDR,   SENINF_MUX3_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX4_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX4_BASE_ADDR,   SENINF_MUX4_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX5_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX5_BASE_ADDR,   SENINF_MUX5_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX6_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX6_BASE_ADDR,   SENINF_MUX6_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX7_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX7_BASE_ADDR,   SENINF_MUX7_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX8_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX8_BASE_ADDR,   SENINF_MUX8_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(ISP_CAM_C_BASE_ADDR)
	MAP_REGION_FLAT(ISP_CAM_C_BASE_ADDR,     ISP_CAM_C_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(FD_TOP_BASE_ADDR)
	MAP_REGION_FLAT(FD_TOP_BASE_ADDR,        FD_TOP_BASE_SIZE,        SECIO_ATTR),
#endif
#if defined(GCE_M_BASE_ADDR) && !defined(GCE_M_ALREADY_MAPPED)
	MAP_REGION_FLAT(GCE_M_BASE_ADDR,         GCE_M_BASE_SIZE,         SECIO_ATTR),
#endif
#if defined(ISP_CAM_A2_BASE_ADDR)
	MAP_REGION_FLAT(ISP_CAM_A2_BASE_ADDR,    ISP_CAM_A2_BASE_SIZE,    SECIO_ATTR),
#endif
#if defined(ISP_CAM_B2_BASE_ADDR)
	MAP_REGION_FLAT(ISP_CAM_B2_BASE_ADDR,    ISP_CAM_B2_BASE_SIZE,    SECIO_ATTR),
#endif
#if defined(ISP_CAM_C2_BASE_ADDR)
	MAP_REGION_FLAT(ISP_CAM_C2_BASE_ADDR,    ISP_CAM_C2_BASE_SIZE,    SECIO_ATTR),
#endif
#if defined(ISP_CAM_SYS_BASE_ADDR)
	MAP_REGION_FLAT(ISP_CAM_SYS_BASE_ADDR,   ISP_CAM_SYS_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SMI_LARB0_BASE_ADDR)
	MAP_REGION_FLAT(SMI_LARB0_BASE_ADDR,     SMI_LARB0_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(SMI_LARB1_BASE_ADDR)
	MAP_REGION_FLAT(SMI_LARB1_BASE_ADDR,     SMI_LARB1_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(SMI_LARB2_BASE_ADDR)
	MAP_REGION_FLAT(SMI_LARB2_BASE_ADDR,     SMI_LARB2_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(SMI_LARB3_BASE_ADDR)
	MAP_REGION_FLAT(SMI_LARB3_BASE_ADDR,     SMI_LARB3_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(SMI_LARB4_BASE_ADDR)
	MAP_REGION_FLAT(SMI_LARB4_BASE_ADDR,     SMI_LARB4_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(SMI_LARB5_BASE_ADDR)
	MAP_REGION_FLAT(SMI_LARB5_BASE_ADDR,     SMI_LARB5_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(SMI_LARB6_BASE_ADDR)
	MAP_REGION_FLAT(SMI_LARB6_BASE_ADDR,     SMI_LARB6_BASE_SIZE,     SECIO_ATTR),
#endif
#if defined(ISP_YUV_CAM_A_BASE_ADDR)
	MAP_REGION_FLAT(ISP_YUV_CAM_A_BASE_ADDR, ISP_YUV_CAM_A_BASE_SIZE, SECIO_ATTR),
#endif
#if defined(ISP_YUV_CAM_B_BASE_ADDR)
	MAP_REGION_FLAT(ISP_YUV_CAM_B_BASE_ADDR, ISP_YUV_CAM_B_BASE_SIZE, SECIO_ATTR),
#endif
#if defined(ISP_YUV_CAM_C_BASE_ADDR)
	MAP_REGION_FLAT(ISP_YUV_CAM_C_BASE_ADDR, ISP_YUV_CAM_C_BASE_SIZE, SECIO_ATTR),
#endif
#if defined(SENINF_MUX9_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX9_BASE_ADDR,   SENINF_MUX9_BASE_SIZE,   SECIO_ATTR),
#endif
#if defined(SENINF_MUX10_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX10_BASE_ADDR,  SENINF_MUX10_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX11_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX11_BASE_ADDR,  SENINF_MUX11_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX12_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX12_BASE_ADDR,  SENINF_MUX12_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX13_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX13_BASE_ADDR,  SENINF_MUX13_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX14_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX14_BASE_ADDR,  SENINF_MUX14_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX15_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX15_BASE_ADDR,  SENINF_MUX15_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX16_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX16_BASE_ADDR,  SENINF_MUX16_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX17_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX17_BASE_ADDR,  SENINF_MUX17_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX18_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX18_BASE_ADDR,  SENINF_MUX18_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX19_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX19_BASE_ADDR,  SENINF_MUX19_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX20_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX20_BASE_ADDR,  SENINF_MUX20_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX21_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX21_BASE_ADDR,  SENINF_MUX21_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(SENINF_MUX22_BASE_ADDR)
	MAP_REGION_FLAT(SENINF_MUX22_BASE_ADDR,  SENINF_MUX22_BASE_SIZE,  SECIO_ATTR),
#endif
#if defined(ISP_INFRA_S)
	MAP_REGION_FLAT(ISP_INFRA_S_BASE_ADDR,   ISP_INFRA_S_BASE_SIZE,   SECIO_ATTR),
#endif
	{0}
};
DECLARE_MTK_MMAP_REGIONS(gz_secio_plat_mmap);

const struct secio_register *get_plat_secio_regs(void)
{
	return plat_secio_regs;
}
